# distributed training
workers: 8
gpus: "0,1,2,3"

# Dataset & paths
data_path: "/mnt/ssd/li/NTU_RGBD_60/nturgb+d_depth_masked"
csv_file_train: "./split/NTU_RGBD_60/cs_train.csv"
csv_file_test: "./split/NTU_RGBD_60/cs_test.csv"
checkpoints: "./checkpoints"
dataset: "NTU_RGBD_60"
task: "Cross-Subject"
modality: "m3d"
image_tmpl: "MDepth-{:08d}.ppm"
img_size: 224
seed: 42

# model
backbone: "resnet50"
num_segments: 3
frame_per_seg: 5
margin: 3

# optimization
epochs: 60
batch_size: 128
dropout: 0.5
lr: 0.01
lr_steps: [25, 40, 50]
momentum: 0.9
weight_decay: 5.0e-4
partial_bn: True
